name: Test

on:
  pull_request_target:
    types: [opened, synchronize, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "aaa ${{ github.event.pull_request.repository }}"
          echo ${{ github.event.repository.default_branch }}
          echo "This PR is opened by ${{ github.event.pull_request.user.login }}"
          echo "This PR is opened by ${{ github.event.pull_request.ref }}"
          
          echo =================
          echo Fork repo: ${{ github.event.pull_request.base.repository }}
          echo Fork Repo Owner: ${{ github.event.pull_request.base.repo.owner.login }}
          echo Fork repo branch: ${{ github.event.pull_request.base.ref }}
          echo Fork Repo Name: ${{ github.event.pull_request.base.repo.name }}
